import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {drawFrame} from '../public/lib/sprites.js';import {champions} from '../public/lib/roster.js';
const manifest=JSON.parse(await readFile(new URL('../public/ASSET_MANIFEST.json',import.meta.url)));const lock=JSON.parse(await readFile(new URL('../authority/RULES_LOCK.json',import.meta.url)));
const sha=b=>createHash('sha256').update(b).digest('hex');
test('All 13 frozen authority files remain byte-identical',async()=>{for(const f of lock.authority)assert.equal(sha(await readFile(new URL('../'+f.path,import.meta.url))),f.sha256,f.path);assert.deepEqual(JSON.parse(await readFile(new URL('../public/champions.json',import.meta.url))).champions,champions);});
test('All ten actual atlas hashes, PNG dimensions and 60 nonuniform frames match manifest',async()=>{assert.equal(manifest.rulesVersion,'0.2.0');assert.equal(manifest.visualVersion,'0.2.0');assert.equal(manifest.sprites.length,10);for(const s of manifest.sprites){const png=await readFile(new URL('../public/'+s.path,import.meta.url));assert.equal(sha(png),s.sha256);assert.equal(png.readUInt32BE(16),s.width);assert.equal(png.readUInt32BE(20),s.height);assert.equal(Object.keys(s.frames).length,6);for(const f of Object.values(s.frames)){const [x,y,w,h]=f.rect;assert(x>=0&&y>=0&&x+w<=s.width&&y+h<=s.height);assert(f.pivot[0]>=0&&f.pivot[0]<=w);assert(f.pivot[1]>=0&&f.pivot[1]<=h);if(f.clipPolygon)for(const [px,py] of f.clipPolygon)assert(px>=0&&py>=0&&px<=w&&py<=h);}}});
test('Renderer uses every exact source rectangle, rectangular crop, optional polygon, and local pivot',()=>{for(const s of manifest.sprites)for(const f of Object.values(s.frames))for(const mirror of [false,true]){const calls=[];const ctx=new Proxy({},{get:(_,name)=>(...args)=>calls.push([name,...args])});const img={id:s.id};drawFrame(ctx,img,f,100,200,.3,mirror);assert.deepEqual(calls.slice(0,4),[['save'],['translate',100,200],['scale',mirror?-.3:.3,.3],['translate',-f.pivot[0],-f.pivot[1]]]);assert(calls.some(c=>c[0]==='rect'&&c.slice(1).join(',')===[0,0,f.rect[2],f.rect[3]].join(',')));assert.equal(calls.filter(c=>c[0]==='clip').length,f.clipPolygon?2:1);assert.deepEqual(calls.find(c=>c[0]==='drawImage'),['drawImage',img,...f.rect,0,0,f.rect[2],f.rect[3]]);assert.equal(calls.at(-1)[0],'restore');}});
test('Arena geometry: all five combat poses and floor anchors fit at 320/390/768/1280 CSS widths',()=>{for(const viewport of [320,390,768,1280]){const width=Math.min(viewport,1120)-(viewport<=600?24:40)-2,height=Math.max(180,Math.min(viewport*.27,280));for(const s of manifest.sprites){const frames=Object.entries(s.frames).filter(([k])=>k!=='portrait').map(([,f])=>f),scale=Math.min((height-26)/Math.max(...frames.map(f=>f.rect[3])),width*.44/Math.max(...frames.map(f=>f.rect[2])));for(const f of frames)for(const seat of [0,1]){const x=width*(seat===0?.26:.74),y=height-16;const left=seat===0?x-f.pivot[0]*scale:x-(f.rect[2]-f.pivot[0])*scale;const right=left+f.rect[2]*scale,top=y-f.pivot[1]*scale;assert(left>=0&&right<=width&&top>=0);assert.equal(top+f.pivot[1]*scale,y);assert(top+f.rect[3]*scale<=height);}}}});
test('Every dice class and overlay referenced by client exists',async()=>{for(let face=1;face<=6;face++)for(const c of ['fail','normal','critical']){const svg=await readFile(new URL(`../public/assets/ui/d6-${face}-${c}.svg`,import.meta.url),'utf8');assert(svg.includes('<svg'));}for(const name of ['blocked','rerolled','selected','critical'])assert((await readFile(new URL(`../public/assets/ui/overlay-${name}.svg`,import.meta.url),'utf8')).includes('<svg'));});

test('Frozen dice assets, manifest and adopted Foundry bytes are unchanged',async()=>{for(const f of manifest.ui)assert.equal(sha(await readFile(new URL('../public/'+f.path,import.meta.url))),f.sha256,f.path);const visual=JSON.parse(await readFile(new URL('../authority/VISUAL_LOCK.json',import.meta.url)));for(const f of visual.files)assert.equal(sha(await readFile(new URL('../'+(f.path==='public/ASSET_MANIFEST.json'?'authority/ASSET_MANIFEST_0.1.0.json':f.path),import.meta.url))),f.sha256,f.path);});
