import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {champions,rulesVersion,visualVersion} from '../public/lib/roster.js';import {decision,seededD6} from '../public/lib/engine.js';import {RoomService} from '../server/rooms.js';import {createApp} from '../server/http.js';
const original=JSON.parse(await readFile(new URL('../authority/champions.json',import.meta.url))).champions;
test('0.2.0: ten unique schema-valid profiles; original six deeply unchanged; no new traits',()=>{assert.equal(rulesVersion,'0.2.0');assert.equal(visualVersion,'0.2.0');assert.equal(champions.length,10);assert.equal(new Set(champions.map(c=>c.id)).size,10);assert.equal(new Set(champions.map(c=>c.name)).size,10);assert.deepEqual(champions.slice(0,6),original);for(const c of champions){assert(/^[a-z]+$/.test(c.id));assert(c.name&&c.weapon.name);assert(Number.isInteger(c.wounds)&&c.wounds>=11&&c.wounds<=16);const w=c.weapon;assert([4,5].includes(w.attackDice));assert([3,4].includes(w.hitThreshold));assert([3,4].includes(w.normalDamage));assert([4,5,6].includes(w.criticalDamage));assert(['balanced','brutal','ceaseless','lethal','shock','rending'].includes(w.trait.id));if(w.trait.id==='lethal')assert.equal(w.trait.threshold,5);}});
test('No new profile strictly dominates a same-trait original profile',()=>{for(const a of champions.slice(6))for(const b of original){if(a.weapon.trait.id!==b.weapon.trait.id)continue;const av=[a.wounds,a.weapon.attackDice,-a.weapon.hitThreshold,a.weapon.normalDamage,a.weapon.criticalDamage],bv=[b.wounds,b.weapon.attackDice,-b.weapon.hitThreshold,b.weapon.normalDamage,b.weapon.criticalDamage];assert(!(av.every((x,i)=>x>=bv[i])&&av.some((x,i)=>x>bv[i])),a.id+' dominates '+b.id);}});
test('Expanded exact percentage adjudication across all ten profiles',()=>{let count=0;for(const a of champions)for(const b of champions)for(let aw=1;aw<=a.wounds;aw++)for(let bw=1;bw<=b.wounds;bw++)for(const attacker of [0,1]){const l=BigInt(a.wounds-aw)*BigInt(b.wounds),r=BigInt(b.wounds-bw)*BigInt(a.wounds);assert.equal(decision([{maxWounds:a.wounds,wounds:aw},{maxWounds:b.wounds,wounds:bw}],attacker).winner,l===r?attacker:l<r?0:1);count++;}assert.equal(count,36450);});
test('All original manifest entries are identical; four additions supply 24 transparent masked frames',async()=>{const old=JSON.parse(await readFile(new URL('../authority/ASSET_MANIFEST_0.1.0.json',import.meta.url))),now=JSON.parse(await readFile(new URL('../public/ASSET_MANIFEST.json',import.meta.url)));assert.deepEqual(now.sprites.slice(0,6),old.sprites);assert.deepEqual(now.ui,old.ui);for(const s of now.sprites.slice(6)){assert(s.alphaZeroFraction>.5);assert.equal(s.mirrorForOpponent,true);assert.equal(s.facing,'right');assert.deepEqual(Object.keys(s.frames),['portrait','idle','strike','block','hit','defeat']);assert(s.sha256&&s.provenance);for(const f of Object.values(s.frames))assert(Number.isInteger(f.durationMs)&&f.durationMs>=0);}const checks=JSON.parse(await readFile(new URL('../docs/release-evidence/atlas-validation.json',import.meta.url)));assert.equal(checks.length,24);assert(checks.every(c=>c.foreignOpaquePixelsAfterMask===0&&c.ownOpaquePixelsClipped===0));});
test('Fourteen synchronized HTTP matches cover each new champion in both seats, old/new, new/new and mirrors',async t=>{const {server}=createApp({service:new RoomService({rng:seededD6(20992)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const origin=`http://127.0.0.1:${server.address().port}`;let serial=0;const newIds=champions.slice(6).map(c=>c.id),pairs=[...newIds.flatMap(id=>[[id,'bastion'],['rivet',id],[id,id]]),['shadowlurker','votive'],['pitjack','ironhaul']];
async function req(path,seat,body){const response=await fetch(origin+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(seat?{Authorization:'Bearer '+seat.token,'X-Connection':seat.connection||''}:{})},body:body===undefined?undefined:JSON.stringify(body)});const d=await response.json();assert(response.ok,JSON.stringify(d));return d;}
for(const pair of pairs){const a=await req('/api/rooms',null,{}),b=await req(`/api/rooms/${a.code}/join`,null,{}),seats=[a,b];for(const p of seats)p.connection=(await req(`/api/rooms/${a.code}/connect`,p,{})).connection;const state=i=>req(`/api/rooms/${a.code}/state`,seats[i]);const send=async(i,action)=>{const s=await state(i);return req(`/api/rooms/${a.code}/command`,seats[i],{matchId:s.id,actionId:`expansion-${++serial}`,expectedVersion:s.version,action});};await send(0,{type:'select',champion:pair[0]});assert.equal((await state(1)).players[0].champion,null);await send(1,{type:'select',champion:pair[1]});let s;
for(let n=0;n<200;n++){s=await state(0);assert.deepEqual(s.players,(await state(1)).players);if(s.phase==='MATCH_RESULT')break;if(['WEAPON_REROLL','COMMAND_REROLL'].includes(s.phase)){for(let i=0;i<2;i++){const v=await state(i);if(v.phase===s.phase&&!v.ready[i])await send(i,{type:s.phase==='WEAPON_REROLL'?'weapon':'command',dice:[]});}}else if(s.phase==='RESOLVE'){const v=await state(s.actor);await send(s.actor,v.legal.find(a=>a.type==='strike'));}else if(s.phase==='BOUT_RESULT'){await send(0,{type:'ready'});await send(1,{type:'ready'});}else throw Error('Unexpected phase '+s.phase);}
assert.equal(s.phase,'MATCH_RESULT');assert.equal(Math.max(...s.players.map(p=>p.score)),3);const id=s.id;await send(0,{type:'rematch'});await send(1,{type:'rematch'});s=await state(0);assert.notEqual(s.id,id);assert.deepEqual(s.players.map(p=>[p.champion,p.score,p.tokens]),[[null,0,2],[null,0,2]]);}
});
