import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../server/http.js';import {RoomService} from '../server/rooms.js';import {seededD6} from '../public/lib/engine.js';
test('Two independent HTTP clients complete synchronized first-to-three and rematch',async t=>{const {server}=createApp({service:new RoomService({rng:seededD6(71234)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const origin=`http://127.0.0.1:${server.address().port}`;let serial=0;
async function req(path,method='POST',body={},seat){const r=await fetch(origin+path,{method,headers:{'Content-Type':'application/json',...(seat?{Authorization:'Bearer '+seat.token,'X-Connection':seat.connection||''}:{})},body:method==='POST'?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};}
const a=(await req('/api/rooms')).data,b=(await req(`/api/rooms/${a.code}/join`)).data;const seats=[a,b];for(const p of seats)p.connection=(await req(`/api/rooms/${p.code}/connect`,'POST',{},p)).data.connection;
const state=async i=>(await req(`/api/rooms/${a.code}/state`,'GET',null,seats[i])).data;
async function send(i,action){const s=await state(i),body={matchId:s.id,actionId:`http-test-${++serial}`,expectedVersion:s.version,action};const r=await req(`/api/rooms/${a.code}/command`,'POST',body,seats[i]);assert.equal(r.status,200,JSON.stringify(r));return r.data;}
await send(0,{type:'select',champion:'cinder'});assert.equal((await state(1)).players[0].champion,null);await send(1,{type:'select',champion:'guttermaw'});
for(let n=0;n<200;n++){let s=await state(0);assert.deepEqual(s.players,(await state(1)).players);if(s.phase==='MATCH_RESULT')break;if(s.phase==='WEAPON_REROLL'||s.phase==='COMMAND_REROLL'){for(let i=0;i<2;i++){const v=await state(i);if(v.phase===s.phase&&!v.ready[i])await send(i,{type:s.phase==='WEAPON_REROLL'?'weapon':'command',dice:[]});}}else if(s.phase==='RESOLVE'){const v=await state(s.actor);await send(s.actor,v.legal.find(a=>a.type==='strike'));}else if(s.phase==='BOUT_RESULT'){await send(0,{type:'ready'});await send(1,{type:'ready'});}}
const end=await state(0);assert.equal(end.phase,'MATCH_RESULT');assert.equal(Math.max(...end.players.map(p=>p.score)),3);await send(0,{type:'rematch'});await send(1,{type:'rematch'});const next=await state(0);assert.notEqual(next.id,end.id);assert.equal(next.phase,'CHAMPION_SELECT');assert.deepEqual(next.players.map(p=>p.tokens),[2,2]);
const invalid=await req(`/api/rooms/${a.code}/state`,'GET',null,{token:'wrong',connection:a.connection});assert.equal(invalid.status,403);assert.equal(invalid.data.snapshot,undefined);
const page=await fetch(origin);assert.equal(page.status,200);assert((await page.text()).includes('Underhive Duel'));
const injection=await req(`/api/rooms/${a.code}/command`,'POST',{matchId:next.id,actionId:'injected-1',expectedVersion:next.version,action:{type:'select',champion:'rivet',rolls:[6,6],score:3}},a);assert.equal(injection.status,409);assert.equal(injection.data.code,'ACTION_FIELDS');
});
