import test from 'node:test';
import assert from 'node:assert/strict';
import {newMatch,transition as step,view,classify,decision,scriptedD6,seededD6,legalActions,invariant} from '../public/lib/engine.js';
import {champions} from '../public/lib/roster.js';
const never=()=>{throw Error('Unexpected randomness');};
function start(a='rivet',b='slagjaw',faces=[6,1,6,4,3,1,6,5,2,1]){let s=newMatch();s=step(s,0,{type:'select',champion:a},never);return step(s,1,{type:'select',champion:b},scriptedD6(faces));}
function pass(s,type='command'){for(let i=0;i<2;i++)if(!s.ready[i])s=step(s,i,{type,dice:[]},never);return s;}
function dice(p,classes){p.dice=classes.map((c,i)=>({id:`d${i}`,face:c==='critical'?6:4,class:c,status:'available',rerolled:null}));}
function combat(a='rivet',b='slagjaw',ca=['critical','normal'],cb=['critical','normal']){const s=start(a,b,[6,1,...Array(champions.find(c=>c.id===a).weapon.attackDice).fill(4),...Array(champions.find(c=>c.id===b).weapon.attackDice).fill(4)]);s.phase='RESOLVE';s.actor=0;dice(s.players[0],ca);dice(s.players[1],cb);return s;}
const reject=(s,seat,a,code)=>{const before=JSON.stringify(s);assert.throws(()=>step(s,seat,a,never),e=>e.code===code);assert.equal(JSON.stringify(s),before);};
test('R01 private simultaneous selection, immutable champions, mirrors',()=>{let s=step(newMatch(),0,{type:'select',champion:'rivet'},never);assert.equal(view(s,1).players[0].champion,null);assert.equal(view(s,1).events.length,0);s=step(s,1,{type:'select',champion:'rivet'},scriptedD6([6,1,6,4,3,1,6,4,3,1]));assert.deepEqual(view(s,1).players.map(p=>p.champion),['rivet','rivet']);reject(s,0,{type:'select',champion:'cinder'},'PHASE');});
test('R02 initiative tie and higher attacker',()=>{const s=start('rivet','slagjaw',[4,4,2,5,1,1,1,1,1,1,1,1]);assert.deepEqual(s.initiative,[[4,4],[2,5]]);assert.equal(s.attacker,1);});
test('R03 natural 1, failure, hit, natural 6',()=>assert.deepEqual([1,2,3,6].map(f=>classify(f,'rivet')),['fail','fail','normal','critical']));
test('R04 reject normal blocking critical atomically',()=>reject(combat('rivet','vesper',['normal'],['critical']),0,{type:'block',die:'d0',target:'d0'},'BLOCK_CLASS'));
test('R05 critical Block removes exactly one normal or critical',()=>{for(const cl of ['normal','critical']){const s=step(combat('rivet','vesper',['critical'],[cl,'normal']),0,{type:'block',die:'d0',target:'d0'},never);assert.equal(s.players[1].dice[0].status,'blocked');assert.equal(s.players[1].dice[1].status,'available');}});
test('R06 Brutal only permits critical Block',()=>{const s=combat('rivet','slagjaw',['normal','critical'],['normal','normal']);reject(s,0,{type:'block',die:'d0',target:'d0'},'BRUTAL_BLOCK_REJECTED');assert.equal(step(s,0,{type:'block',die:'d1',target:'d0'},never).players[1].dice[0].status,'blocked');});
test('R07 Ceaseless same-face subsets; mixed rejected',()=>{const s=start('guttermaw','slagjaw',[6,1,1,2,2,4,6,4,4,4,4]);const ids=s.players[0].dice.map(d=>d.id);reject(s,0,{type:'weapon',dice:[ids[0],ids[1]]},'CEASELESS_FACE');for(const chosen of [[ids[1]],[ids[1],ids[2]]]){const t=step(s,0,{type:'weapon',dice:chosen},scriptedD6(chosen.map(()=>5)));assert.equal(t.players[0].dice.filter(d=>d.rerolled).length,chosen.length);}});
test('R08 Balanced die cannot receive Command',()=>{let s=start('bastion','slagjaw');const id=s.players[0].dice[0].id;s=step(s,0,{type:'weapon',dice:[id]},scriptedD6([1]));reject(s,0,{type:'command',dice:[id]},'ALREADY_REROLLED');assert.equal(s.players[0].tokens,2);});
test('R09 multi-die Command rejects before any roll or expenditure',()=>{const s=start();reject(s,0,{type:'command',dice:s.players[0].dice.slice(0,2).map(d=>d.id)},'COMMAND_LIMIT');let t=step(s,0,{type:'command',dice:[s.players[0].dice[0].id]},never);assert.equal(t.players[0].tokens,2);assert.equal(view(t,1).choices[0],null);t=step(t,1,{type:'command',dice:[]},scriptedD6([3]));assert.equal(t.players[0].tokens,1);assert.equal(t.players[0].commandUsed,true);});
test('R10 Rending promotes once after final rolls',()=>{const s=pass(start('cinder','slagjaw',[6,1,6,4,4,2,1,6,4,2,1]));assert.deepEqual(s.players[0].dice.map(d=>d.class),['critical','critical','normal','fail','fail']);assert.equal(s.events.filter(e=>e.type==='RENDING_PROMOTION').length,1);});
test('R11 rerolling away only critical prevents Rending',()=>{let s=start('cinder','slagjaw',[6,1,6,4,4,2,1,6,4,2,1]);s=step(s,0,{type:'command',dice:[s.players[0].dice[0].id]},never);s=step(s,1,{type:'command',dice:[]},scriptedD6([1]));assert.equal(s.events.some(e=>e.type==='RENDING_PROMOTION'),false);});
test('R12 Lethal 5+ classifications',()=>assert.deepEqual([1,3,5,6].map(f=>classify(f,'vesper')),['fail','normal','critical','critical']));
test('R13 Shock normal priority, critical fallback, once per bout',()=>{let s=combat('rivet','bastion',['critical','critical'],['critical','normal','normal']);s=step(s,0,{type:'strike',die:'d0'},never);assert.equal(s.players[1].dice[1].status,'blocked');s=step(s,1,{type:'strike',die:'d2'},never);s=step(s,0,{type:'strike',die:'d1'},never);assert.equal(s.events.filter(e=>e.type==='SHOCK_DISCARD').length,1);assert.equal(s.players[1].dice[0].status,'available');const t=step(combat('rivet','bastion',['critical'],['critical']),0,{type:'strike',die:'d0'},never);assert.equal(t.players[1].dice[0].status,'blocked');});
test('R14 Shock does not activate on critical Block',()=>{const s=step(combat(),0,{type:'block',die:'d0',target:'d0'},never);assert.equal(s.players[0].shockUsed,false);assert.equal(s.events.some(e=>e.type==='SHOCK_DISCARD'),false);});
test('R15 empty attacker skips to defender and no empty turns',()=>{let s=pass(start('rivet','slagjaw',[6,1,1,1,1,1,4,4,1,1]));assert.equal(s.actor,1);s=step(s,1,{type:'strike',die:s.players[1].dice[0].id},never);assert.equal(s.actor,1);s=step(s,1,{type:'strike',die:s.players[1].dice[1].id},never);assert.equal(s.phase,'BOUT_RESULT');});
test('R16/R32 lethal strike ends immediately with one point, no retaliation',()=>{const s=combat();s.players[1].wounds=5;const t=step(s,0,{type:'strike',die:'d0'},never);assert.equal(t.result.reason,'OOA');assert.equal(t.players[0].wounds,12);assert.equal(t.players[0].score,1);assert.equal(t.actor,null);reject(t,1,{type:'strike',die:'d0'},'PHASE');});
test('R17 percentage decision beats raw damage',()=>assert.equal(decision([{maxWounds:12,wounds:2},{maxWounds:16,wounds:3}],0).winner,1));
test('R18 exact 50% or zero loss awards attacker',()=>{for(const wounds of [[6,8],[12,16]])for(const a of [0,1])assert.equal(decision([{maxWounds:12,wounds:wounds[0]},{maxWounds:16,wounds:wounds[1]}],a).winner,a);});
test('R19 bout resets wounds/flags but preserves match tokens',()=>{let s=combat();s.phase='BOUT_RESULT';s.ready=[false,false];s.players[0].tokens=1;s.players[0].commandUsed=true;s.players[0].shockUsed=true;s.players[0].wounds=2;s=step(s,0,{type:'ready'},never);s=step(s,1,{type:'ready'},scriptedD6([6,1,4,4,4,4,4,4,4,4]));assert.equal(s.players[0].wounds,12);assert.equal(s.players[0].tokens,1);assert.equal(s.players[0].commandUsed,false);assert.equal(s.players[0].shockUsed,false);});
test('R20 stop immediately at 3:0 or 3:2',()=>{for(const other of [0,2]){const s=combat();s.bout=3+other;s.players[0].score=2;s.players[1].score=other;s.players[1].wounds=1;const t=step(s,0,{type:'strike',die:'d0'},never);assert.equal(t.phase,'MATCH_RESULT');invariant(t);reject(t,0,{type:'ready'},'PHASE');}});
const worked=[
{rolls:[6,2,6,4,3,1,6,5,2,1],cmd:[null,null],extra:[],moves:[[0,0,11],[1,0,6],[0,1,7],[0,2,3]],score:[1,0],tokens:[2,2],reason:'DECISION'},
{rolls:[1,5,5,4,2,1,6,6,4,1],cmd:[2,null],extra:[3],moves:[[1,0,6],[0,0,12],[1,1,0]],score:[1,1],tokens:[1,2],reason:'OOA'},
{rolls:[4,2,6,5,2,1,6,4,2,1],cmd:[3,2],extra:[4,5],moves:[[0,0,11],[1,0,6],[0,1,7],[1,2,2],[0,3,3]],score:[1,2],tokens:[0,1],reason:'DECISION'},
{rolls:[3,6,6,6,3,1,6,5,3,1],cmd:[null,2],extra:[4],moves:[[1,0,6],[0,0,11],[1,2,2],[0,1,6],[0,2,2]],score:[2,2],tokens:[0,0],reason:'DECISION'},
{rolls:[6,1,6,6,4,2,6,5,4,1],cmd:[null,null],extra:[],moves:[[0,0,11],[1,0,6],[0,1,6],[1,2,2],[0,2,2]],score:[3,2],tokens:[0,0],reason:'DECISION'}];
test('R21 full frozen five-bout worked match: every row and intermediate wounds',()=>{let s;for(let b=0;b<5;b++){const f=worked[b];if(b===0)s=start('rivet','slagjaw',f.rolls);else{s=step(s,0,{type:'ready'},never);s=step(s,1,{type:'ready'},scriptedD6(f.rolls));}const rng=scriptedD6(f.extra);for(let seat=0;seat<2;seat++)s=step(s,seat,{type:'command',dice:f.cmd[seat]===null?[]:[s.players[seat].dice[f.cmd[seat]].id]},rng);for(const [seat,index,expected] of f.moves){assert.equal(s.actor,seat);s=step(s,seat,{type:'strike',die:s.players[seat].dice[index].id},never);assert.equal(s.players[1-seat].wounds,expected);}assert.deepEqual(s.players.map(p=>p.score),f.score);assert.deepEqual(s.players.map(p=>p.tokens),f.tokens);assert.equal(s.result.reason,f.reason);invariant(s);}assert.equal(s.phase,'MATCH_RESULT');assert.equal(s.bout,5);});
test('R22 damage below half never reclassifies retained dice',()=>{const s=combat('slagjaw','rivet',['critical'],['normal','critical']);s.players[1].wounds=10;const before=s.players[1].dice.map(d=>d.class);const t=step(s,0,{type:'strike',die:'d0'},never);assert.equal(t.players[1].wounds,4);assert.deepEqual(t.players[1].dice.map(d=>d.class),before);});
test('R23 new second Command request cannot spend in same bout',()=>{let s=start();s=step(s,0,{type:'command',dice:[s.players[0].dice[0].id]},never);s=step(s,1,{type:'command',dice:[]},scriptedD6([4]));reject(s,0,{type:'command',dice:[s.players[0].dice[1].id]},'PHASE');s.phase='COMMAND_REROLL';s.ready=[false,false];reject(s,0,{type:'command',dice:[s.players[0].dice[1].id]},'COMMAND_BOUT_LIMIT');});
// R24 receipt idempotence is executed in rooms.test.js after local engine validation.
test('R25 zero tokens cannot be replenished or spent',()=>{const s=start();s.players[0].tokens=0;reject(s,0,{type:'command',dice:[s.players[0].dice[0].id]},'NO_TOKENS');});
test('R26 free reroll + Command on another die',()=>{let s=start('bastion','slagjaw');const ids=s.players[0].dice.map(d=>d.id);s=step(s,0,{type:'weapon',dice:[ids[0]]},scriptedD6([2]));assert.equal(s.players[0].commandUsed,false);assert.equal(s.players[0].tokens,2);s=step(s,0,{type:'command',dice:[ids[1]]},never);s=step(s,1,{type:'command',dice:[]},scriptedD6([6]));assert.equal(s.players[0].dice.filter(d=>d.rerolled).length,2);assert.equal(s.players[0].tokens,1);});
test('R27 pass preserves tokens and next-bout allowance',()=>{let s=pass(start());assert.equal(s.players[0].tokens,2);assert.equal(s.players[0].commandUsed,false);s.phase='BOUT_RESULT';s.ready=[false,false];s=step(s,0,{type:'ready'},never);s=step(s,1,{type:'ready'},scriptedD6([6,1,4,4,4,4,4,4,4,4]));assert.equal(s.players[0].tokens,2);assert.equal(s.players[0].commandUsed,false);});
test('R28 same raw loss is not percentage tie',()=>assert.equal(decision([{maxWounds:12,wounds:8},{maxWounds:16,wounds:12}],0).winner,1));
test('R29 different raw losses, same percentage: attacker',()=>{for(const a of [0,1])assert.equal(decision([{maxWounds:12,wounds:9},{maxWounds:16,wounds:12}],a).winner,a);});
test('R30 exhaustive surviving states agree with independent BigInt rational oracle',()=>{let count=0;for(const a of champions)for(const b of champions)for(let aw=1;aw<=a.wounds;aw++)for(let bw=1;bw<=b.wounds;bw++)for(const attacker of [0,1]){const left=BigInt(a.wounds-aw)*BigInt(b.wounds),right=BigInt(b.wounds-bw)*BigInt(a.wounds);assert.equal(decision([{maxWounds:a.wounds,wounds:aw},{maxWounds:b.wounds,wounds:bw}],attacker).winner,left===right?attacker:left<right?0:1);count++;}assert.equal(count,12800);});
test('R31 Command creating critical triggers Rending only after both lock',()=>{let s=start('cinder','slagjaw',[6,1,4,4,2,2,1,4,4,2,1]);s=step(s,0,{type:'command',dice:[s.players[0].dice[4].id]},never);assert.equal(s.events.some(e=>e.type==='RENDING_PROMOTION'),false);s=step(s,1,{type:'command',dice:[]},scriptedD6([6]));assert.equal(s.players[0].dice[0].promoted,true);assert.equal(s.players[0].dice.filter(d=>d.class==='critical').length,2);});
test('Deterministic local full match for each of all 36 champion pairs (not balance screening)',()=>{for(const a of champions)for(const b of champions){const run=()=>{const rng=seededD6(71234);let s=newMatch();s=step(s,0,{type:'select',champion:a.id},rng);s=step(s,1,{type:'select',champion:b.id},rng);for(let n=0;s.phase!=='MATCH_RESULT'&&n<200;n++){if(s.phase==='WEAPON_REROLL'||s.phase==='COMMAND_REROLL'){const type=s.phase==='WEAPON_REROLL'?'weapon':'command';for(let i=0;i<2;i++)if(!s.ready[i]){s=step(s,i,{type,dice:[]},rng);if(s.phase!==(type==='weapon'?'WEAPON_REROLL':'COMMAND_REROLL'))break;}}else if(s.phase==='RESOLVE')s=step(s,s.actor,legalActions(s,s.actor)[0],rng);else if(s.phase==='BOUT_RESULT'){s=step(s,0,{type:'ready'},rng);s=step(s,1,{type:'ready'},rng);}invariant(s);}assert.equal(s.phase,'MATCH_RESULT');return s;};assert.deepEqual(run(),run());}});
