import test from 'node:test';import assert from 'node:assert/strict';
import {createApp} from '../server/http.js';import {RoomService} from '../server/rooms.js';import {seededD6} from '../public/lib/engine.js';import {RemoteMatch} from '../public/lib/remote.js';
test('Actual browser transport module: two client instances, polling, full match and seat restore',async t=>{
 const {server}=createApp({service:new RoomService({rng:seededD6(71234)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,realFetch=globalThis.fetch,realStorage=globalThis.sessionStorage;const storage=new Map();globalThis.sessionStorage={setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k),removeItem:k=>storage.delete(k)};globalThis.fetch=(url,init)=>realFetch(new URL(url,base),init);const clients=[];
 t.after(async()=>{for(const c of clients)c.running=false;await new Promise(r=>setTimeout(r,1100));globalThis.fetch=realFetch;if(realStorage===undefined)delete globalThis.sessionStorage;else globalThis.sessionStorage=realStorage;await new Promise(r=>server.close(r));});
 const statuses=[];const a=await RemoteMatch.open(null,()=>{},m=>statuses.push(m)),b=await RemoteMatch.open(a.code,()=>{},m=>statuses.push(m));clients.push(a,b);a.running=false;b.running=false; // Poll explicitly below to make the protocol fixture deterministic, rather than timing-dependent.
 const sync=async()=>{for(const c of clients.slice(0,2)){const response=await fetch(`/api/rooms/${c.code}/state`,{headers:{Authorization:'Bearer '+c.token,'X-Connection':c.connection}});assert.equal(response.status,200);c.accept(await response.json());}};
 await sync();await a.send({type:'select',champion:'vesper'});await sync();assert.equal(b.snapshot().players[0].champion,null);await b.send({type:'select',champion:'bastion'});await sync();
 for(let i=0;i<200&&a.snapshot().phase!=='MATCH_RESULT';i++){const s=a.snapshot();if(s.phase==='WEAPON_REROLL'||s.phase==='COMMAND_REROLL'){for(const [seat,c] of clients.slice(0,2).entries()){if(c.snapshot().phase===s.phase&&!c.snapshot().ready[seat]){await c.send({type:s.phase==='WEAPON_REROLL'?'weapon':'command',dice:[]});await sync();}}}else if(s.phase==='RESOLVE'){const c=clients[s.actor];await c.send(c.snapshot().legal.find(a=>a.type==='strike'));await sync();}else if(s.phase==='BOUT_RESULT'){await a.send({type:'ready'});await sync();await b.send({type:'ready'});await sync();}}
 assert.equal(a.snapshot().phase,'MATCH_RESULT');assert.deepEqual(a.snapshot().players,b.snapshot().players);const restored=await RemoteMatch.restore({code:b.code,seat:b.seat,token:b.token},()=>{},m=>statuses.push(m));clients.push(restored);restored.running=false;assert.deepEqual(restored.snapshot().players,b.snapshot().players);assert.notEqual(restored.connection,b.connection);assert.equal(a.pending,null);assert.equal(b.pending,null);assert.deepEqual(statuses,[]);
});
