import {randomBytes,randomInt,timingSafeEqual} from 'node:crypto';
import {newMatch,transition,view,RuleError,invariant} from '../public/lib/engine.js';
const token=()=>randomBytes(24).toString('base64url');
const equal=(a,b)=>typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
const fail=(code,message)=>{throw new RuleError(code,message);};
const canonical=x=>x&&typeof x==='object'?Array.isArray(x)?'['+x.map(canonical).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}':JSON.stringify(x);
const terminal=s=>['MATCH_RESULT','ABANDONED'].includes(s.phase);
/** One Node process is the authority. Never run multiple independent replicas.
 * HTTP intent handling has no await between validation and commit. Rooms and receipts
 * exist only for their live lifecycle; restart returns ROOM_GONE, never guessed state.
 */
export class RoomService{
 constructor({now=()=>Date.now(),rng=()=>randomInt(1,7),leaseMs=8000,graceMs=60000,retentionMs=900000,maxRooms=200}={}){this.rooms=new Map();this.now=now;this.rng=rng;this.leaseMs=leaseMs;this.graceMs=graceMs;this.retentionMs=retentionMs;this.maxRooms=maxRooms;}
 create(){this.tick();if(this.rooms.size>=this.maxRooms)fail('CAPACITY','The alpha is at room capacity. Please try again later.');let code;const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';do{code=Array.from({length:6},()=>alphabet[randomInt(alphabet.length)]).join('');}while(this.rooms.has(code));const r={code,state:newMatch(token()),seats:[this.seat(),null],pausedFrom:null,deadline:null,lastActivity:this.now(),terminalAt:null,receipts:new Map()};this.rooms.set(code,r);return {code,seat:0,token:r.seats[0].token};}
 seat(){return {token:token(),connection:null,connected:false,lastSeen:this.now()};}
 room(code){const r=this.rooms.get(code);if(!r)fail('ROOM_GONE','Room not found. It may have expired or the service restarted. Create a new room.');return r;}
 join(code){this.tick();const r=this.room(code);if(r.seats[1])fail('ROOM_FULL','This room already has two players. Reconnect using your original tab.');if(r.state.phase==='ABANDONED')fail('ABANDONED','This room has ended.');r.seats[1]=this.seat();r.state.version++;r.lastActivity=this.now();return {code,seat:1,token:r.seats[1].token};}
 auth(r,secret){const i=r.seats.findIndex(s=>s&&equal(s.token,secret));if(i<0)fail('INVALID_SEAT','Invalid private seat token. The room code cannot reclaim a seat.');return i;}
 connect(code,secret){this.tick();const r=this.room(code),seat=this.auth(r,secret),p=r.seats[seat];p.connection=token();p.connected=true;p.lastSeen=this.now();r.lastActivity=this.now();r.state.version++;this.resume(r);return {connection:p.connection,snapshot:this.snapshot(r,seat)};}
 current(code,secret,connection){const r=this.room(code),seat=this.auth(r,secret);if(!equal(r.seats[seat].connection,connection))fail('CONNECTION_REPLACED','This seat was opened in another tab. Use the newest connection.');return {r,seat};}
 poll(code,secret,connection){this.tick();const {r,seat}=this.current(code,secret,connection);const p=r.seats[seat];if(!p.connected)fail('RECONNECT_REQUIRED','Connection timed out. Reconnect to resume your seat.');p.lastSeen=this.now();if(r.state.phase==='CHAMPION_SELECT'||!r.seats[1])r.lastActivity=this.now();return this.snapshot(r,seat);}
 disconnect(code,secret,connection){const {r,seat}=this.current(code,secret,connection);this.markDisconnected(r,seat);return {ok:true};}
 markDisconnected(r,seat){const p=r.seats[seat];if(!p?.connected)return;p.connected=false;r.state.version++;if(r.seats[1]&&!terminal(r.state)&&r.deadline===null){r.pausedFrom=r.state.phase;r.deadline=this.now()+this.graceMs;}}
 resume(r){if(r.deadline!==null&&r.seats.every(p=>p?.connected)&&this.now()<r.deadline){r.deadline=null;r.pausedFrom=null;}}
 tick(){const now=this.now();for(const [code,r] of this.rooms){for(let i=0;i<2;i++){const p=r.seats[i];if(p?.connected&&now-p.lastSeen>=this.leaseMs)this.markDisconnected(r,i);}if(r.deadline!==null&&now>=r.deadline){r.state.phase='ABANDONED';r.state.actor=null;r.state.result=null;r.state.version++;r.state.events.push({id:r.state.events.length+1,bout:r.state.bout,type:'ABANDONED',reason:'Disconnect grace period expired. No competitive winner.'});r.deadline=null;r.pausedFrom=null;r.terminalAt=now;}
 if((terminal(r.state)&&now-(r.terminalAt??r.lastActivity)>=this.retentionMs)||((!r.seats[1]||r.state.phase==='CHAMPION_SELECT')&&now-r.lastActivity>=this.retentionMs))this.rooms.delete(code);}}
 snapshot(r,seat){const s=view(r.state,seat);return {...s,phase:!r.seats[1]&&s.phase==='CHAMPION_SELECT'?'WAITING':s.phase,code:r.code,connected:r.seats.map(p=>!!p?.connected),paused:r.deadline!==null,pausedFrom:r.pausedFrom,disconnectDeadline:r.deadline,serverTime:this.now(),legal:r.deadline!==null?[]:s.legal};}
 command(code,secret,connection,envelope){this.tick();const {r,seat}=this.current(code,secret,connection);const allowed=['matchId','actionId','expectedVersion','action'];if(!envelope||Object.keys(envelope).some(k=>!allowed.includes(k))||typeof envelope.matchId!=='string'||typeof envelope.actionId!=='string'||!/^[-\w]{8,100}$/.test(envelope.actionId)||!Number.isInteger(envelope.expectedVersion))fail('ENVELOPE','Invalid command envelope.');
 const key=seat+':'+envelope.actionId,payload=canonical(envelope),cached=r.receipts.get(key);if(cached){if(cached.payload!==payload)fail('ACTION_CONFLICT','This action ID was already used with a different payload.');return {...structuredClone(cached.receipt),duplicate:true,snapshot:this.snapshot(r,seat)};}
 if(envelope.matchId!==r.state.id)fail('MATCH_ID','This command belongs to another match. Refresh your state.');if(!r.seats[seat].connected)fail('RECONNECT_REQUIRED','Reconnect before acting.');if(!r.seats[1]&&envelope.action?.type!=='leave')fail('WAITING','Wait for a second player to join.');if(r.deadline!==null&&envelope.action?.type!=='leave')fail('PAUSED','The match is paused for a disconnected player.');if(!r.seats.every(p=>p?.connected)&&envelope.action?.type!=='leave')fail('WAITING','Wait for both players to connect.');if(envelope.expectedVersion!==r.state.version)fail('STALE_VERSION','State changed. Review the current dice and try again.');
 const before=r.state;const next=transition(before,seat,envelope.action,this.rng);invariant(next);r.state=next;r.lastActivity=this.now();r.seats[seat].lastSeen=this.now();if(terminal(next)){r.terminalAt??=this.now();r.deadline=null;r.pausedFrom=null;}const receipt={actionId:envelope.actionId,matchId:envelope.matchId,committedVersion:next.version,accepted:true};r.receipts.set(key,{payload,receipt});
 if(next.phase==='MATCH_RESULT'&&next.ready.every(Boolean)){r.state=newMatch(token());r.state.version=next.version+1;r.terminalAt=null;r.deadline=null;r.pausedFrom=null;/* Keep recent preceding-match receipts so an ambiguous rematch retry is safe. */if(r.receipts.size>1000){const old=[...r.receipts.keys()].slice(0,r.receipts.size-1000);for(const k of old)r.receipts.delete(k);}}
 return {...receipt,duplicate:false,snapshot:this.snapshot(r,seat)};
 }
}
