// public/champions.json is the single authored roster. This generated module keeps
// the existing browser compatibility of ordinary ES modules, without JSON imports.
import {readFile,writeFile} from 'node:fs/promises';
const data=JSON.parse(await readFile(new URL('../public/champions.json',import.meta.url)));
await writeFile(new URL('../public/lib/roster.js',import.meta.url),'// Generated by scripts/sync-roster.mjs; edit public/champions.json.\nconst data = '+JSON.stringify(data,null,2)+`;\nexport const rulesVersion=data.rulesVersion;\nexport const visualVersion='0.2.0';\nexport const champions=Object.freeze(data.champions.map(c=>Object.freeze(c)));\nexport const roster=Object.fromEntries(champions.map(c=>[c.id,c]));\n`);
